### ISSUE TITLE
Not working on python 3.9

### ISSUE THREAD

**Issue by rafaelribeiroo** [thbzzz/chromium_cookie_decrypt#1]
Hello, how r u? I hope fine, well... can u explain me why this code not works in python 3.9? I'm using sublime text with anaconda and line 91 returns syntax error, print below.

![2021-01-11_05-34](https://user-images.githubusercontent.com/19275140/104159831-ce090c80-53ce-11eb-9069-ec3fb41523c0.png)

**Comment by thbzzz** [comment]
Hello, line 91 is valid Python code (even in 3.9), it works fine using CLI or vscode.
Did you try outside of sublime ?

**Comment by rafaelribeiroo** [comment]
Yeah, I'm already try in terminal  too, when I run the code returns nothing (print below)

![image](https://user-images.githubusercontent.com/19275140/104161669-01996600-53d2-11eb-8b04-7e93b58c74a3.png)

**Comment by rafaelribeiroo** [comment]
I tested your code in https://extendsclass.com/python-tester.html and returns error syntax in line 91 too (print below).

![image](https://user-images.githubusercontent.com/19275140/104162709-e3cd0080-53d3-11eb-8c96-1d485a3c841a.png)

**Comment by rafaelribeiroo** [comment]
> Hello, line 91 is valid Python code (even in 3.9), it works fine using CLI or vscode.
> Did you try outside of sublime ?

In your machine are working the script?

**Comment by thbzzz** [comment]
The issue seems to be happening only for Python <= 3.4 (see https://github.com/bastibe/transplant/issues/37).
But indeed, instead of doing `[*list]` I could do simply do `list`, it's just cleaner and more logical.
I am commiting the fix and closing the issue, thanks for your time!

**Comment by rafaelribeiroo** [comment]
Now its returning unicodedecodeerror, do u know what could be?

![image](https://user-images.githubusercontent.com/19275140/104423228-96c86600-555c-11eb-962f-c3d82cb4328c.png)
